### ISSUE TITLE
Feature: in `iswap_with`, if only one other option, just directly swap

### ISSUE THREAD

**Issue by IndianBoy42** [mizlan/iswap.nvim#25]
As the title says. Technically the first/only other option is always going to be `a` (or the first configured hint key), but we can still cut it out i think.

**Comment by mizlan** [comment]
I've been thinking about this. How about automatically swapping in general when there are only two items?

**Comment by IndianBoy42** [comment]
If we're going further we could also not show the hints if you do `iswap` when there is just one argument/thing to swap

**Comment by mizlan** [comment]
I like the "autoswap" idea more. I'll work on that.

**Comment by mizlan** [comment]
Try it out with `setup { ... autoswap = true}` (see README). Should work now.

**Comment by IndianBoy42** [comment]
I think you have left some debug prints in `iswap_with`? it seems the ranges to be swapped are getting printed. Otherwise it works perfectly

**Comment by mizlan** [comment]
Are you referring to seeing this?

https://github.com/mizlan/iswap.nvim/blob/307ec70956ab5bf29a7adb0bd1d7a21e5c6b42f4/lua/iswap.lua#L90

This one is purposely meant to be seen by the user. (I should probably word it to something more end-user-friendly). If you're seeing another message other than this, do you have `debug = true` in your `setup()` function? Otherwise those messages shouldn't show.

**Comment by IndianBoy42** [comment]
![image](https://user-images.githubusercontent.com/5981889/130553677-7bdcba15-d9f3-4d2d-977b-24d1891eb7c9.png)

I get something like this everytime i do `:ISwapWith`

**Comment by IndianBoy42** [comment]
![image](https://user-images.githubusercontent.com/5981889/130553743-9fd85bd8-b165-483c-9c25-5d31c4fa124c.png)

The number of lines printed is proportional to the number of options to swap

**Comment by mizlan** [comment]
Wow, that is embarrassing. Should be fixed now!
