### ISSUE TITLE
[Feature Request]: Delete argument

### ISSUE THREAD

**Issue by ovidius72** [mizlan/iswap.nvim#33]
Hi. Thanks for this useful plugin.
I would like to have a similar functionality to delete an argument, element in the list or parameter.
Would it be possible to implement something like this ?
Thanks.

**Comment by mizlan** [comment]
I think https://github.com/nvim-treesitter/nvim-treesitter-textobjects does what you want.

**Comment by ovidius72** [comment]
Does it let you peek the argument you want to delete the same way this plugin does ?
I'm pretty sure it can't.

**Comment by mizlan** [comment]
You would be correct. It would not be too difficult to add, but could you elaborate a bit more on how it would work? For example: user runs command, user sees highlight, user hits confirmation key.

**Comment by ovidius72** [comment]
Yes exactly.
A command similar to `:ISwap`,  could be for example `:IDelete` that let you pick the item you want to delete. 
Another cool feature in my opinion would be to be able to call these command from the same line or in the same block, not sure if that's possible.
Anyway, thanks.

**Comment by JoseConseco** [comment]
Imo it would be better if you used  https://github.com/mfussenegger/nvim-treehopper  - for this kind of tasks. With that plugin, you can change, delete, cut any node that you can target with  HOP like labels.

**Comment by lyndhurst** [comment]
Hi @mizlan ,

I found this thread looking for similar functionality. Actually I am rather looking for a "select" operation that then lets you do whatever you need like delete, yank ...

Imho, it would be a nice addition to your plugin, because it would answer a need that `nvim-treehopper` does not. With `TSTH`, you can target any object around your current cursor position. What `iswap.nvim` could add, is remote target seeking like [targets.vim](https://github.com/wellle/targets.vim) does.

To be more descriptive, my cursor is on function argument 1, and without moving the cursor, I can select argument 3 in a few keystrokes. I use `targets.vim` mostly for this, and better in-quote selection, but it fails with first and last item/argument of a list/function. For what I experimented, your plugin (or `treesitter`) is pretty accurate for that.

On top of being able to select, it could be cool to add a behavior like `targets.vim`, or `vi"` that detects the closest potential target when the cursor is near, but outside the list. I see there is a `lookahead` parameter in `TS-textobjects` but maybe that is pushing it :)

I am just starting to transition from vim, so maybe I am missing something, in which case, thank you for letting me know.

Thank you for your time, and this plugin.
